Update for discord.js v12  compatibility (#6)
* Update Discord peer dependency to v12

* Update .gitignore to standard node gitignore

* Update RoleCall.js for use in v12 Discord.js

* Update README.md to reflect v12 compatability

* Fix undefined reference to client in raw event handler

* Improvements to handler and initializer design, improve documentation

Implement new features introduced to d.js v11 branch (like removeReaction)

* Add separate collections for role-emoji pairs and roles

roleEmojiPairs is mapped by emoji, roles is mapped by Role ID

* Change discord.js peer to 12.5.1

This is a suggestion, I believe any stable v12 build should work but this is the one I finalized this update on. If issues are encountered on an earlier discord.js build, consider updating to 12.5.1 and see if the problem is resolved